# Generated by Django 5.1.7 on 2025-07-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_score_highest_score_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
