# Generated by Django 5.1.7 on 2025-08-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_deadline_schedule",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_today_schedule",
            field=models.BooleanField(default=True),
        ),
    ]
