# Generated by Django 5.1.6 on 2025-03-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="chatting",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chatbots.answer"
            ),
        ),
    ]
