# Generated by Django 5.1.6 on 2025-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0002_answer_alter_chatting_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="date",
            field=models.DateField(),
        ),
    ]
