# Generated by Django 4.2.19 on 2025-03-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0003_alter_answer_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="date",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="answer",
            name="method",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="answer",
            name="tag",
            field=models.CharField(max_length=20),
        ),
    ]
