# Generated by Django 4.2.19 on 2025-03-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0004_alter_answer_date_alter_answer_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatting",
            name="answer",
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
