# Generated by Django 5.1.7 on 2025-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0005_alter_chatting_answer_delete_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatting",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="chatting",
            name="answer",
            field=models.JSONField(null=True),
        ),
    ]
