# Generated by Django 5.1.6 on 2025-02-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tag',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag', to='schedules.tag'),
        ),
    ]
