# Generated by Django 5.1.6 on 2025-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_schedule_tag_schedule_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='schedules.tag'),
        ),
    ]
