# Generated by Django 5.1.7 on 2025-04-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_alter_schedule_tag_alter_schedule_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="tag",
            new_name="tags",
        ),
    ]
