# Generated by Django 5.1.7 on 2025-04-01 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_rename_tag_schedule_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="tags",
        ),
        migrations.AddField(
            model_name="schedule",
            name="tag",
            field=models.ManyToManyField(related_name="schedule", to="schedules.tag"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
