# Generated by Django 5.1.7 on 2025-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_remove_schedule_tags_schedule_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
