# Generated by Django 5.1.7 on 2025-08-24 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webpushsubscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Web Push 구독",
                "verbose_name_plural": "Web Push 구독들",
            },
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="auth",
            field=models.CharField(
                help_text="Web Push 인증을 위한 키",
                max_length=200,
                verbose_name="인증 키",
            ),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="endpoint",
            field=models.URLField(
                help_text="Web Push 서비스의 구독 엔드포인트 URL",
                unique=True,
                verbose_name="구독 엔드포인트",
            ),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="p256dh",
            field=models.TextField(
                help_text="Web Push 암호화를 위한 P-256 DH 공개키",
                verbose_name="P-256 DH 공개키",
            ),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webpush_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
