# Generated by Django 5.1.7 on 2025-08-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_webpushsubscription_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebPushSubscription",
        ),
    ]
